In [14]:
import pandas as pd
import numpy as np

In [15]:
import warnings
with warnings.catch_warnings():
    warnings.simplefilter("ignore")

In [16]:

#dataset

data = [
    [29,"Sales Executive",4800,3,4,1],
    [35,"Research Scientist",6000,4,8,0],
    [40,"Laboratory Technician",3400,2,6,0],
    [28,"Sales Executive",4300,3,3,1],
    [45,"Manager",11000,4,15,0],
    [25,"Research Scientist",3500,1,2,1],
    [50,"Manager",12000,4,20,0],
    [30,"Sales Executive",5000,2,5,0],
    [37,"Laboratory Technician",3100,2,9,0],
    [26,"Research Scientist",4500,3,2,1]
]

column_names = [
    "Age",
    "JobRole",
    "MonthlyIncome",
    "JobSatisfaction",
    "YearsAtCompany",
    "Attrition"
]

df = pd.DataFrame(data, columns=column_names)

In [17]:
df.drop_duplicates(inplace=True)

df.dropna(inplace=True)

print(df)

display(df)

   Age                JobRole  MonthlyIncome  JobSatisfaction  YearsAtCompany  \
0   29        Sales Executive           4800                3               4
1   35     Research Scientist           6000                4               8
2   40  Laboratory Technician           3400                2               6
3   28        Sales Executive           4300                3               3
4   45                Manager          11000                4              15
5   25     Research Scientist           3500                1               2
6   50                Manager          12000                4              20
7   30        Sales Executive           5000                2               5
8   37  Laboratory Technician           3100                2               9
9   26     Research Scientist           4500                3               2

   Attrition
0          1
1          0
2          0
3          1
4          0
5          1
6          0
7          0
8          0
9          1

,Age,JobRole,MonthlyIncome,JobSatisfaction,YearsAtCompany,Attrition
0,29,Sales Executive,4800,3,4,1
1,35,Research Scientist,6000,4,8,0
2,40,Laboratory Technician,3400,2,6,0
3,28,Sales Executive,4300,3,3,1
4,45,Manager,11000,4,15,0
5,25,Research Scientist,3500,1,2,1
6,50,Manager,12000,4,20,0
7,30,Sales Executive,5000,2,5,0
8,37,Laboratory Technician,3100,2,9,0
9,26,Research Scientist,4500,3,2,1

In [18]:
display(df.head())

,Age,JobRole,MonthlyIncome,JobSatisfaction,YearsAtCompany,Attrition
0,29,Sales Executive,4800,3,4,1
1,35,Research Scientist,6000,4,8,0
2,40,Laboratory Technician,3400,2,6,0
3,28,Sales Executive,4300,3,3,1
4,45,Manager,11000,4,15,0

In [19]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["JobRole"] = encoder.fit_transform(df["JobRole"])

display(df.head())

   Age  JobRole  MonthlyIncome  JobSatisfaction  YearsAtCompany  Attrition
0   29        3           4800                3               4          1
1   35        2           6000                4               8          0
2   40        0           3400                2               6          0
3   28        3           4300                3               3          1
4   45        1          11000                4              15          0

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [21]:
X = df.drop("Attrition", axis=1)

y = df["Attrition"]

display(X.head())

display(y.head())

   Age  JobRole  MonthlyIncome  JobSatisfaction  YearsAtCompany
0   29        3           4800                3               4
1   35        2           6000                4               8
2   40        0           3400                2               6
3   28        3           4300                3               3
4   45        1          11000                4              15

0    1
1    0
2    0
3    1
4    0
Name: Attrition, dtype: int64

In [22]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data")

display(X_train)

print("Testing Data")

display(X_test)

Training Data

   Age  JobRole  MonthlyIncome  JobSatisfaction  YearsAtCompany
5   25        2           3500                1               2
0   29        3           4800                3               4
7   30        3           5000                2               5
2   40        0           3400                2               6
9   26        2           4500                3               2
4   45        1          11000                4              15
3   28        3           4300                3               3
6   50        1          12000                4              20

Testing Data

   Age  JobRole  MonthlyIncome  JobSatisfaction  YearsAtCompany
8   37        0           3100                2               9
1   35        2           6000                4               8

In [23]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [24]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [25]:
y_pred = knn.predict(X_test)

print("Predicted Values")

print(y_pred)

print("Actual Values")

print(y_test.values)

Predicted Values
[1 1]
Actual Values
[0 0]

In [26]:
from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred)

print(report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       2.0
           1       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [27]:
new_employee = [[32, 2, 5500, 3, 5]]

new_employee = scaler.transform(new_employee)

prediction = knn.predict(new_employee)

print("Predicted Attrition :", prediction[0])

Predicted Attrition : 1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(