In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [ ]:
data = [
    [230.1, 37.8, 69.2, 22.1],
    [44.5, 39.3, 45.1, 10.4],
    [17.2, 45.9, 69.3, 9.3],
    [151.5, 41.3, 58.5, 18.5],
    [180.8, 10.8, 58.4, 12.9],
    [8.7, 48.9, 75.0, 7.2],
    [57.5, 32.8, 23.5, 11.8],
    [120.2, 19.6, 11.6, 13.2],
    [144.1, 16.0, 40.3, 15.6],
    [111.6, 12.6, 37.9, 12.2]
]

column_names = [
    "TV Budget",
    "Radio Budget",
    "Newspaper Budget",
    "Sales"
]

df = pd.DataFrame(data, columns=column_names)

In [ ]:
#data cleaning

df.drop_duplicates(inplace=True)

df.dropna(inplace=True)

print(df)

display(df)

   TV Budget  Radio Budget  Newspaper Budget  Sales
0      230.1          37.8              69.2   22.1
1       44.5          39.3              45.1   10.4
2       17.2          45.9              69.3    9.3
3      151.5          41.3              58.5   18.5
4      180.8          10.8              58.4   12.9
5        8.7          48.9              75.0    7.2
6       57.5          32.8              23.5   11.8
7      120.2          19.6              11.6   13.2
8      144.1          16.0              40.3   15.6
9      111.6          12.6              37.9   12.2

   TV Budget  Radio Budget  Newspaper Budget  Sales
0      230.1          37.8              69.2   22.1
1       44.5          39.3              45.1   10.4
2       17.2          45.9              69.3    9.3
3      151.5          41.3              58.5   18.5
4      180.8          10.8              58.4   12.9
5        8.7          48.9              75.0    7.2
6       57.5          32.8              23.5   11.8
7      120.2          19.6              11.6   13.2
8      144.1          16.0              40.3   15.6
9      111.6          12.6              37.9   12.2

In [ ]:
display(df.head())

   TV Budget  Radio Budget  Newspaper Budget  Sales
0      230.1          37.8              69.2   22.1
1       44.5          39.3              45.1   10.4
2       17.2          45.9              69.3    9.3
3      151.5          41.3              58.5   18.5
4      180.8          10.8              58.4   12.9

In [ ]:
X = df.drop("Sales", axis=1)

y = df["Sales"]

print("Input Features")
display(X.head())

print("Output")
display(y.head())

Input Features

   TV Budget  Radio Budget  Newspaper Budget
0      230.1          37.8              69.2
1       44.5          39.3              45.1
2       17.2          45.9              69.3
3      151.5          41.3              58.5
4      180.8          10.8              58.4

Output

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: Sales, dtype: float64

In [ ]:
model = LinearRegression()

model.fit(X, y)

LinearRegression()

In [ ]:
print("Intercept :", model.intercept_)

print("Coefficients :")

for feature, value in zip(X.columns, model.coef_):
    print(feature, ":", value)

Intercept : 3.2207019780103145
Coefficients :
TV Budget : 0.07045872318593276
Radio Budget : 0.17635400280880517
Newspaper Budget : -0.0571155509362321

In [ ]:
new_data = [[150, 30, 40]]

prediction = model.predict(new_data)

print("Predicted Sales :", prediction[0])

Predicted Sales : 16.7955085027151

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
predicted = model.predict(X)

result = pd.DataFrame({
    "Actual Sales": y,
    "Predicted Sales": predicted
})

display(result)

   Actual Sales  Predicted Sales
0          22.1        22.147039
1          10.4        10.710916
2           9.3         8.569133
3          18.5        17.837359
4          12.9        14.528714
5           7.2         8.173737
6          11.8        11.714274
7          13.2        14.483839
8          15.6        13.893711
9          12.2        11.141277

In [ ]:
score = model.score(X, y)

print("Model Accuracy:", score)

Model Accuracy: 0.9408001446975406